### ISSUE TITLE
[BUG] - Enabling and Disabling video camera on Video Control buttons does not resume the stream for other users in the channel.

### ISSUE THREAD

**Issue by haroonkhan335** [AgoraIO-Community/VideoUIKit-Flutter#115] opened 2022-12-26 10:49 UTC
Enabling and Disabling Video camera does not work properly to other users that have joined the channel. When you disable the video camera, it works for all the users including the local user. But when re-enabled, only camera enables for the local user and the stream for other users does not update at all. Though the videoStateChanged callback does calls on all the users devices on the stream.

To Reproduce

1. Run the basic example project with Agora UIKIT and Agora UIKIT control buttons.
2. Disable the video. Works for all users.
3. Enable back the video. Only works for local user and the stream does not get updated for other users on the line.

Expected behavior
Enabling the video should resume the stream for all the users who have joined the channel.

**Smartphone (please complete the following information):**
 - Device: Any Android Device
 - OS: Any iOS device.
- Version: latest on pub.dev

**Comment by haroonkhan335** [comment] 2023-01-05 18:17
> @Meherdeep are you able to replicate this issue?

This can be replicated by the simple example from the library.

**Comment by Meherdeep** [comment] 2023-01-05 21:19
@haroonkhan335 I tried running the sample code and I was not able to reproduce this error. Can you please share your Agora SDK logs?

**Comment by haroonkhan335** [comment] 2023-01-06 06:33
> @haroonkhan335 I tried running the sample code and I was not able to reproduce this error. Can you please share your Agora SDK logs?

Logs in terms of what? Agora logs a lot I am not sure which particular you need.

Did you make sure there are multiple users on the video call while testing?

**Comment by Meherdeep** [comment] 2023-01-10 21:15
@haroonkhan335 The logs generated while you're trying to disable/enable the local video would be good. 

Yes, I tried with multiple remote users on the call.

**Comment by Meherdeep** [comment] 2023-01-11 20:47
@haroonkhan335 Sorry, I ran some more tests with cross platform devices and I was able to reproduce this error. We will release a fix for this soon.

**Closed** 2023-01-19 15:00 UTC
Labels: bug

**Comment by Meherdeep** [comment] 2023-01-19 17:08
@haroonkhan335 Hopefully, the new release fixes this issue. Please give it a try, and feel free to reopen this issue if the issue still persists.
